import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/sections/footer';
import Hero from '../components/sections/hero';
import Main from '../components/sections/main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <div className="hidden md:block">
        <Main />
      </div>
      <Footer />
    </div>
  );
}
